[config]
skip_core_tasks = true

[env]
OVMF_DIR = "/usr/share/ovmf"

[tasks.build]
dependencies = [
  {name = "build", path = "kernel"},
  {name = "build", path = "bootloader"},
]

[tasks.run]
dependencies = ["build"]
run_task = "qemu"

[tasks.disk]
run_task = {name = ["disk-rm", "disk-create", "disk-mount", "disk-copy"], fork = true, cleanup_task = "disk-umount"}

[tasks.disk-rm]
ignore_errors = true
script = '''
rm disk.img
'''

[tasks.disk-create]
script = '''
echo "disk-create"
qemu-img create -f raw disk.img 200M
mkfs.fat -n "MUSIX OS" -s 2 -f 2 -F 32 -R 32 disk.img
'''

[tasks.disk-mount.linux]
script = '''
echo "disk-mount.linux"
mkdir -p ./mnt
sudo mount -o loop disk.img ./mnt
'''

[tasks.disk-mount.mac]
script = '''
#!/usr/bin/env bash
mkdir -p ./mnt
disk=$(hdiutil attach -nomount disk.img)
echo $disk
mount_msdos $disk ./mnt
'''

[tasks.disk-copy]
script = '''
sudo mkdir -p ./mnt/EFI/BOOT
sudo cp ./bootloader/target/x86_64-unknown-uefi/debug/bootloader.efi ./mnt/EFI/BOOT/BOOTX64.EFI
sudo cp ./kernel/kernel.elf ./mnt/kernel.elf
'''

[tasks.prepare-ovmf]
script = '''
mkdir -p ./uefi-firmware
cp ${OVMF_DIR}/OVMF_CODE.fd ${OVMF_DIR}/OVMF_VARS.fd ./uefi-firmware/
'''

[tasks.qemu]
# dependenciesに"prepare-ovmf"を入れるとローカルからOVMFを引っ張ってきてくれる
dependencies = ["disk"]
script = '''
qemu-system-x86_64 \
    -m 1G \
    -drive if=pflash,format=raw,file=./uefi-firmware/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=./uefi-firmware/OVMF_VARS.fd \
    -drive format=raw,media=disk,index=0,file=disk.img \
    -device nec-usb-xhci,id=xhci \
    -device usb-mouse -device usb-kbd \
    -device isa-debug-exit \
    -monitor stdio \
    -display gtk
'''

[tasks.qemu.mac]
# dependenciesに"prepare-ovmf"を入れるとローカルからOVMFを引っ張ってきてくれる
dependencies = ["disk"]
script = '''
qemu-system-x86_64 \
    -m 1G \
    -drive if=pflash,format=raw,file=./uefi-firmware/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=./uefi-firmware/OVMF_VARS.fd \
    -drive format=raw,media=disk,index=0,file=disk.img \
    -device nec-usb-xhci,id=xhci \
    -device usb-mouse -device usb-kbd \
    -device isa-debug-exit \
    -monitor stdio \
'''

[tasks.disk-umount]
ignore_errors = true
script = '''
sudo umount ./mnt && rmdir ./mnt
'''

