[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1"
x86_64 = "0.14.10"
spin = { version = "0.9.0", features = ["lock_api", "mutex"] }

[features]
